language: java

matrix:
  include:
    - jdk: oraclejdk9
      env: JDK='Oracle JDK 9'
    - env:
      - JDK='Oracle JDK 10'
      - NO_JACOCO='true'
      before_install: wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && . ./install-jdk.sh -F 10
    - env:
      - JDK='Oracle JDK 11'
      - NO_JACOCO='true'
      before_install: wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && . ./install-jdk.sh -F 11
    - env:
      - JDK='Oracle JDK 12'
      - NO_JACOCO='true'
      before_install: wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && . ./install-jdk.sh -F 12

cache:
  directories:
    - $HOME/.m2

sudo: false

services:
  - docker
  - postgresql

install: true

script:
  - "./mvnw -version"
  - "./mvnw clean dependency:list test -Pall-dbs${NO_JACOCO:+',no-jacoco'} -Dsort -U"
